import React from 'react'

const BottomDashboardIcon = ({
  width,
  height,
  className,
  handleNavigation
}) => {
  return (
    <svg
      onClick={() => handleNavigation('/dashboard')}
      id="dashboard-icon"
      xmlns="http://www.w3.org/2000/svg"
      width={width}
      height={height}
      className={className}
      viewBox="0 0 224 229"
    >
      <rect
        id="program1"
        x="6"
        y="6"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#d7daff"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="program2"
        x="87"
        y="6"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#d7daff"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="program3"
        x="168"
        y="6"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#d7daff"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="program4"
        x="6"
        y="90"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#d7daff"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="program5"
        x="87"
        y="90"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#adb2ef"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="program6"
        x="168"
        y="90"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#8188d5"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="program7"
        x="6"
        y="173"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#d7daff"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="program8"
        x="87"
        y="173"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#8188d5"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="program9"
        x="168"
        y="173"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#6369bc"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
    </svg>
  )
}

export default BottomDashboardIcon
