import React from 'react'

const DashboardIcon = ({ width, height, className }) => {
  return (
    <svg
      id="exercise-database-icon"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      width={width}
      height={height}
      viewBox="0 0 224 229"
    >
      <rect
        id="exercise1"
        x="6"
        y="6"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="exercise2"
        x="87"
        y="6"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="exercise3"
        x="168"
        y="6"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="exercise4"
        x="6"
        y="90"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="exercise5"
        x="87"
        y="90"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="exercise6"
        x="168"
        y="90"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="exercise7"
        x="6"
        y="173"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="exercise8"
        x="87"
        y="173"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
      <rect
        id="exercise9"
        x="168"
        y="173"
        width="50"
        height="50"
        rx="14"
        fill="none"
        stroke="#f8f8f8"
        strokeMiterlimit="10"
        strokeWidth="12"
      />
    </svg>
  )
}

export default DashboardIcon
